In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv(r'D:/Data/NLP/TextFiles/moviereviews.tsv',sep='\t')

In [13]:
df.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [14]:
from IPython.display import Markdown,display
Markdown('> ' + df['review'][0])

> how do films like mouse hunt get into theatres ? 
isn't there a law or something ? 
this diabolical load of claptrap from steven speilberg's dreamworks studio is hollywood family fare at its deadly worst . 
mouse hunt takes the bare threads of a plot and tries to prop it up with overacting and flat-out stupid slapstick that makes comedies like jingle all the way look decent by comparison . 
writer adam rifkin and director gore verbinski are the names chiefly responsible for this swill . 
the plot , for what its worth , concerns two brothers ( nathan lane and an appalling lee evens ) who inherit a poorly run string factory and a seemingly worthless house from their eccentric father . 
deciding to check out the long-abandoned house , they soon learn that it's worth a fortune and set about selling it in auction to the highest bidder . 
but battling them at every turn is a very smart mouse , happy with his run-down little abode and wanting it to stay that way . 
the story alternates between unfunny scenes of the brothers bickering over what to do with their inheritance and endless action sequences as the two take on their increasingly determined furry foe . 
whatever promise the film starts with soon deteriorates into boring dialogue , terrible overacting , and increasingly uninspired slapstick that becomes all sound and fury , signifying nothing . 
the script becomes so unspeakably bad that the best line poor lee evens can utter after another run in with the rodent is : " i hate that mouse " . 
oh cringe ! 
this is home alone all over again , and ten times worse . 
one touching scene early on is worth mentioning . 
we follow the mouse through a maze of walls and pipes until he arrives at his makeshift abode somewhere in a wall . 
he jumps into a tiny bed , pulls up a makeshift sheet and snuggles up to sleep , seemingly happy and just wanting to be left alone . 
it's a magical little moment in an otherwise soulless film . 
a message to speilberg : if you want dreamworks to be associated with some kind of artistic credibility , then either give all concerned in mouse hunt a swift kick up the arse or hire yourself some decent writers and directors . 
this kind of rubbish will just not do at all . 


In [15]:
len(df)

2000

In [16]:
df.isnull().sum()

label      0
review    35
dtype: int64

In [18]:
df.dropna(inplace=True)
len(df)

1965

In [19]:
blanks=[]
for i,lb,rev in df.itertuples():
    if type(rev)==str:
        if rev.isspace():
            blanks.append(i)
print(len(blanks),'blanks :',blanks)

27 blanks : [57, 71, 147, 151, 283, 307, 313, 323, 343, 351, 427, 501, 633, 675, 815, 851, 977, 1079, 1299, 1455, 1493, 1525, 1531, 1763, 1851, 1905, 1993]


In [20]:
df.drop(blanks,inplace=True)
len(df)

1938

In [21]:
df['label'].value_counts()

neg    969
pos    969
Name: label, dtype: int64

----

In [72]:
X = df['review']
y = df['label']

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

----

In [86]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import LinearSVC

In [76]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

---

In [77]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',RandomForestClassifier())])

In [78]:
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('rfc', RandomForestClassifier())])

In [79]:
predict = text_clf.predict(X_test)

In [81]:
def predict_model(X_test,y_test,predict):
    print(confusion_matrix(y_test,predict))
    print('\n')
    print(classification_report(y_test,predict))
    print('\n')
    print(accuracy_score(y_test,predict))

In [82]:
predict_model(X_test,y_test,predict)

[[266  42]
 [119 213]]


              precision    recall  f1-score   support

         neg       0.69      0.86      0.77       308
         pos       0.84      0.64      0.73       332

    accuracy                           0.75       640
   macro avg       0.76      0.75      0.75       640
weighted avg       0.77      0.75      0.75       640



0.7484375


----

In [83]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',AdaBoostClassifier())])
text_clf.fit(X_train,y_train)
predict = text_clf.predict(X_test)
predict = text_clf.predict(X_test)
predict_model(X_test,y_test,predict)

[[235  73]
 [ 77 255]]


              precision    recall  f1-score   support

         neg       0.75      0.76      0.76       308
         pos       0.78      0.77      0.77       332

    accuracy                           0.77       640
   macro avg       0.77      0.77      0.77       640
weighted avg       0.77      0.77      0.77       640



0.765625


----

In [87]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',LinearSVC())])
text_clf.fit(X_train,y_train)
predict = text_clf.predict(X_test)
predict = text_clf.predict(X_test)
predict_model(X_test,y_test,predict)

[[259  49]
 [ 49 283]]


              precision    recall  f1-score   support

         neg       0.84      0.84      0.84       308
         pos       0.85      0.85      0.85       332

    accuracy                           0.85       640
   macro avg       0.85      0.85      0.85       640
weighted avg       0.85      0.85      0.85       640



0.846875
