In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv(r'D:/Data/NLP/TextFiles/smsspamcollection.tsv',sep='\t')

In [11]:
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [12]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [18]:
blanks = []
for i,lb,msg,leng,pun in df.itertuples():
    if type(msg)==str:
        if msg.isspace():
            blanks.append(i)

In [19]:
print(len(blanks),'blanks: ',blanks)

0 blanks:  []


In [20]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

----

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X = df['message']
y = df['label']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

----

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import LinearSVC

----

In [27]:
from sklearn.pipeline import Pipeline

In [54]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',RandomForestClassifier(n_estimators=100))])

In [55]:
text_clf.fit(X_train,y_train);

In [56]:
predict = text_clf.predict(X_test)

In [57]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [58]:
print(confusion_matrix(y_test,predict))
print('\n')
print(classification_report(y_test,predict))
print('\n')
print(accuracy_score(y_test,predict))

[[1593    0]
 [  42  204]]


              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      1593
        spam       1.00      0.83      0.91       246

    accuracy                           0.98      1839
   macro avg       0.99      0.91      0.95      1839
weighted avg       0.98      0.98      0.98      1839



0.9771615008156607


----

In [63]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',AdaBoostClassifier(n_estimators=100))])
text_clf.fit(X_train,y_train);
predict = text_clf.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,predict))
print('\n')
print(classification_report(y_test,predict))
print('\n')
print(accuracy_score(y_test,predict))

[[1584    9]
 [  25  221]]


              precision    recall  f1-score   support

         ham       0.98      0.99      0.99      1593
        spam       0.96      0.90      0.93       246

    accuracy                           0.98      1839
   macro avg       0.97      0.95      0.96      1839
weighted avg       0.98      0.98      0.98      1839



0.9815116911364872


----

In [64]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',GradientBoostingClassifier(n_estimators=100))])
text_clf.fit(X_train,y_train);
predict = text_clf.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,predict))
print('\n')
print(classification_report(y_test,predict))
print('\n')
print(accuracy_score(y_test,predict))

[[1589    4]
 [  42  204]]


              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      1593
        spam       0.98      0.83      0.90       246

    accuracy                           0.97      1839
   macro avg       0.98      0.91      0.94      1839
weighted avg       0.98      0.97      0.97      1839



0.9749864056552474


----

In [65]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('rfc',LinearSVC())])
text_clf.fit(X_train,y_train);
predict = text_clf.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,predict))
print('\n')
print(classification_report(y_test,predict))
print('\n')
print(accuracy_score(y_test,predict))

[[1586    7]
 [  12  234]]


              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      1593
        spam       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



0.989668297988037
