In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'D:/Data/NLP/TextFiles/npr.csv')

In [3]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

----

# Preprocessing

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [6]:
dtm = cv.fit_transform(df['Article'])

In [7]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [14]:
type(cv.get_feature_names())

list

In [22]:
cv.get_feature_names_out()[5000]

'bask'

In [24]:
len(cv.get_feature_names_out())

54777

----

# LDA

In [8]:
from sklearn.decomposition import LatentDirichletAllocation

In [9]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [10]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

----

In [30]:
# Showing Random stored words
import random

for i in range(10):
    random1 = random.randint(0,54777)
    print(cv.get_feature_names_out()[random1])

feature
expected
bystrom
moralist
calorie
insulate
surgically
shakespeare
consultant
bookstore


----

# Top words per topic

In [73]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [36]:
# We have 7 topics
len(LDA.components_)

7

In [37]:
# Words in first topic
len(LDA.components_[0])

54777

In [35]:
first_topic = LDA.components_[0]

In [43]:
#argsort return indices that will sort the array (lowest to highest)
top_ten_words_1 = LDA.components_[0].argsort()[-10:]

In [44]:
for index in top_ten_words_1:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says


In [53]:
for index,topic in enumerate(LDA.components_):
    print(f'Top 20 words in Topic:{index}')
    word = []
    for i in topic.argsort()[-20:]:
        word.append(cv.get_feature_names_out()[i])
    print(word)
    print('\n')

Top 20 words in Topic:0
['president', 'state', 'tax', 'insurance', 'trump', 'companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


Top 20 words in Topic:1
['white', 'according', 'attack', 'reported', 'war', 'military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


Top 20 words in Topic:2
['little', 'know', 'don', 'year', 'make', 'way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


Top 20 words in Topic:3
['world', 'research', 'university', 'percent', 'care', 'time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


Top 20 words in Topic:4
['donald', 'political', 'states', 'law', 'just', 'voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 

In [81]:
topic_dict = {0:'Economy',1:'National Security',2:'Daily Life',3:'Healthcare',4:'Politics',5:'Hobbies',6:'Data studies'}

# Attaching discoverd labels to Articles

In [54]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [55]:
dtm.shape

(11992, 54777)

In [56]:
topic_results = LDA.transform(dtm)

In [58]:
# Total articles and labels
topic_results.shape

(11992, 7)

In [63]:
# Probabilities that in which topic should this article be present
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [64]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [70]:
# Gives the index of topic which has highest probability. Here it is Topic 1
topic_results[0].argmax()

1

In [67]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [68]:
df['Topic'] = topic_results.argmax(axis=1)

In [69]:
df.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2

In [85]:
df['label']=df['Topic'].map(topic_dict)
df.head(50)

Article  Topic  \
0   In the Washington of 2016, even when the polic...      1   
1     Donald Trump has used Twitter  —   his prefe...      1   
2     Donald Trump is unabashedly praising Russian...      1   
3   Updated at 2:50 p. m. ET, Russian President Vl...      1   
4   From photography, illustration and video, to d...      2   
5   I did not want to join yoga class. I hated tho...      3   
6   With a   who has publicly supported the debunk...      3   
7   I was standing by the airport exit, debating w...      2   
8   If movies were trying to be more realistic, pe...      3   
9   Eighteen years ago, on New Year’s Eve, David F...      2   
10  For years now, some of the best, wildest, most...      5   
11  For years now, some of the best, wildest, most...      5   
12  The Colorado River is like a giant bank accoun...      2   
13  For the last installment of NPR’s holiday reci...      2   
14  Being overweight can raise your blood pressure...      3   
15  Who’s the YouTube star of 2016? Adele singing ...      5   
16  Here’s a quick roundup of some of the   you ma...      2   
17  Ben Johnston doesn’t follow the rules of music...      5   
18  David Bowie, Prince and George Michael are all...      5   
19  In November, the typically straitlaced Office ...      1   
20  This is the time of year when everybody is mak...      5   
21  Terrorist attacks, hurricanes, a divisive U. S...      6   
22  We all experience stress at work, no matter th...      6   
23  When John Fahey recorded The New Possibility i...      5   
24  This year was one of   hacks, exploding smartp...      6   
25  From West Virginia to Wyoming, coal country ov...      4   
26  Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      1   
27  On the morning of Jan. 1, Los Angeles resident...      1   
28  In September, reproductive endocrinologist Joh...      3   
29  In an effort to take advantage of the intimate...      3   
30  Much has been said about the physical and psyc...      3   
31  Editor’s note: This post includes language tha...      4   
32  The   movement, which has been associated with...      4   
33  On New Year’s Day, Portland restaurant Ava Gen...      2   
34  U. S. Supreme Court Chief Justice John Roberts...      4   
35  When Octavia Spencer first read the script for...      5   
36  If you find yourself at a loss to name even on...      2   
37  By day, Nicola Berlinsky and sisters Lisa Pime...      5   
38  It’s that time of year again, when I atone for...      5   
39  For those of us at NPR, 2016 was   of big news...      5   
40  Though many of us lamented the   saga of this ...      4   
41  With so much attention paid to   women in 2016...      3   
42  As the 115th Congress is sworn in Tuesday, Rep...      4   
43  Democrats may have lost the House and the Sena...      4   
44  There’s more methane gas in the atmosphere tha...      6   
45  A Jewish farming couple from Canada says it ha...      2   
46  As Donald Trump prepares to become president, ...      0   
47  The Islamic State issued a statement on Monday...      1   
48  On a September day in 1940 while much of Europ...      2   
49  Hundreds came out New Year’s Day to ride the t...      2   

                label  
0   National Security  
1   National Security  
2   National Security  
3   National Security  
4          Daily Life  
5          Healthcare  
6          Healthcare  
7          Daily Life  
8          Healthcare  
9          Daily Life  
10            Hobbies  
11            Hobbies  
12         Daily Life  
13         Daily Life  
14         Healthcare  
15            Hobbies  
16         Daily Life  
17            Hobbies  
18            Hobbies  
19  National Security  
20            Hobbies  
21       Data studies  
22       Data studies  
23            Hobbies  
24       Data studies  
25           Politics  
26  National Security  
27  National Security  
28         Healthcare  
29         Healthcare  
30         Healthcare  
31           